### ISSUE TITLE
Evaluate design systems available for react-native

### ISSUE THREAD

**Issue by mykhailodanilenko** [OwnTube-tv/web-client#110]
Evaluate design system libs that are available on react-native similar to https://tamagui.dev/ in terms of extensibility and usability on all platforms

**Comment by mkl-adsn** [comment]
Closing this one for now. Now specific design system used as template during design. Mykhailo can decide if he thinks using one would help during front end implementation. Figma file is set up with variables and easy to adjust if needed.
