### ISSUE TITLE
Add "Featured instances" block on the homepage

### ISSUE THREAD

**Issue by mykhailodanilenko** [OwnTube-tv/web-client#115]
When no instance has been selected, show a block with "Featured instances" the same way as on joinpeertube.org homepage.
Put the featured instances in a .json file - array of objects with name, short description and logo.

![Image](https://github.com/user-attachments/assets/a08987b8-e00a-4df1-a98d-3a4b9174a710)

**Comment by mkl-adsn** [comment]
@mblomdahl Added design for instances block for you to check out. 

https://www.figma.com/proto/f15L42P8qyLqNkzm0Eeo8G/Owntube?page-id=0%3A1&node-id=116-4865&viewport=-4385%2C2392%2C1.03&t=RYe1G8NrCX1sx5aR-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=116%3A4865&show-proto-sidebar=1
