### ISSUE TITLE
Video controls design implementation

### ISSUE THREAD

**Issue by mykhailodanilenko** [OwnTube-tv/web-client#118]
Use video player components https://www.figma.com/design/f15L42P8qyLqNkzm0Eeo8G/Owntube?node-id=16-704&t=hCyPFHcz8XjZy41R-1
to implement the video controls overlay in https://www.figma.com/design/f15L42P8qyLqNkzm0Eeo8G/Owntube?node-id=12-2107&t=hCyPFHcz8XjZy41R-1.
Add fullscreen functionality + volume control.

**Comment by mkl-adsn** [comment]
@mykhailodanilenko Added to Figma and here: 

![Image](https://github.com/user-attachments/assets/86695b4a-8459-47b5-9041-d465b7a3fe8f)
