### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by mykhailodanilenko** [OwnTube-tv/web-client#164]
1. Handle offline/online status change
2. Proxy errors (301 etc)
3. Video didnt load on video page
4. Connection dropped or timed out
5. 5XX errors from the server
6. Forbidden errors or unauthenticated

Need UI for: 1,2,4 (functionally offline) - whole page notice with buttons disabled or grey disabled overlay?
3,5 (server offline for some reason) - inform the user of the situation and offer options
6 - inform the user of permission error and offer to give up

**Comment by mkl-adsn** [comment]
Added disabled state for buttons and video player faild to load video: https://www.figma.com/design/f15L42P8qyLqNkzm0Eeo8G/Owntube?node-id=2-466&t=KYlUj6pngVhB0APk-1
https://www.figma.com/design/f15L42P8qyLqNkzm0Eeo8G/Owntube?node-id=909-14702&t=KYlUj6pngVhB0APk-1

The rest I think I need to know a bit more detail about

**Comment by mkl-adsn** [comment]
Added examples in Figma.
Offline: https://www.figma.com/design/f15L42P8qyLqNkzm0Eeo8G/Owntube?node-id=925-19906&t=Y7ZXHPhd2Uo6hYzQ-1
Forbidden: https://www.figma.com/design/f15L42P8qyLqNkzm0Eeo8G/Owntube?node-id=925-20181&t=Y7ZXHPhd2Uo6hYzQ-1

**Comment by mkl-adsn** [comment]
@mykhailodanilenko Made some slight updates the draft @mblomdahl posted yesterday. One variant for no thumbnail loaded, one for no video info fetchabe at all. Any other cases we need to support?

https://www.figma.com/design/f15L42P8qyLqNkzm0Eeo8G/Owntube?node-id=1031-12837&t=vdB9kgNy04WroJEY-1
