### ISSUE TITLE
UI for "other sites" on the landing page

### ISSUE THREAD

**Issue by mykhailodanilenko** [OwnTube-tv/web-client#166]
The landing page features an "Other sites" link which is curently not as beautiful as it can be (see screenshot) ![Image](https://github.com/user-attachments/assets/27a28ee0-302b-42e8-8e42-71436c2cc01b)

**Comment by mkl-adsn** [comment]
Made a suggestion a bit different from the current setup. Thoughts? https://www.figma.com/design/f15L42P8qyLqNkzm0Eeo8G/Owntube?node-id=116-4865&t=KYlUj6pngVhB0APk-1

**Comment by mkl-adsn** [comment]
Keep recent instances, make as cards? Max 3? Search box below.
