### ISSUE TITLE
List/grid view switch design implementation

### ISSUE THREAD

**Issue by mykhailodanilenko** [OwnTube-tv/web-client#175]

**Comment by mkl-adsn** [comment]
Switch design added: https://www.figma.com/proto/f15L42P8qyLqNkzm0Eeo8G/Owntube?page-id=0%3A1&node-id=16-1036&viewport=-3162%2C-10769%2C1.22&t=F6WlBVIWLWo3IyO8-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=116%3A4865&show-proto-sidebar=1
