### ISSUE TITLE
Web fork customization

### ISSUE THREAD

**Issue by mykhailodanilenko** [OwnTube-tv/web-client#202]
Need to be able to customize the 1. app icon 2. bundle id 3. app name on per-fork basis through GH environment settings (each web instance should be able to be different from others in these 3 regards).

**Comment by ar9708** [comment]
Idea, how to point out where the fork configs are in their GitHub repo environment variables (for consumption by GHA pipeline):

```bash
CLIENT_CUSTOMIZATIONS_REPO=git@github.com:OwnTube-tv/client-customizations.git
CLIENT_CUSTOMIZATIONS_FILE=config.mashatube.env
```
