### ISSUE TITLE
Unreachable "All channels" button on TV home screen

### ISSUE THREAD

**Issue by mblomdahl** [OwnTube-tv/web-client#237]
When navigating with the remote on the home screen, there is no intuitive way that I can think of that would allow the user to press the "All channels" button in the sticky top bar.
<img width="1109" alt="image" src="https://github.com/user-attachments/assets/dbc48765-4ea2-4c97-ad13-ac36e87d0db4">

In my estimation, it would be better if it was 1) greyed out/visually disabled or 2) eliminated on TV. What's your take on this, @mykhailodanilenko ?

P.S. Same applies to "All playlists", "All categories" et cetera, by the same reasoning.

**Comment by ar9708** [comment]
Resolved in #239
