### ISSUE TITLE
Pressing the "back" button on the apple remote closes the app to background, instead of navigating back

### ISSUE THREAD

**Issue by mblomdahl** [OwnTube-tv/web-client#244]
When I press the "back" button here: ![IMG_2107 Small](https://github.com/user-attachments/assets/35ab852f-4135-4751-a3b4-dbe2474be74c), I leave the MishaTube app and find myself on the app overview in my TV. Instead, I would expect it to work as in the YouTube app; if you watch a video and then press "back", it returns to the previous screen.

**Comment by ar9708** [comment]
Fixed in #239
