### ISSUE TITLE
Mock-up of simple landing page which lists categories and items within

### ISSUE THREAD

**Issue by ar9708** [OwnTube-tv/web-client#3]
- [x] Use Figma and make it easily shareable ← https://www.figma.com/file/77wSzKzV4cbKzttKpG4vPw/Untitled?type=design&node-id=0%3A1&mode=design&t=ZcSPPNIUARQPFM7M-1
- [ ] Mock-ups på design, hur ser landningssidan ut? Ska se vettigt ut i alla förekommande formfaktorer. 2 varianter för tablet, 2 varianter för desktop, och 4 varianter för mobiler (Android/iPhone, stående/liggande)
- [ ] Vilka komponenter behöver sidan? Förmodligen någon yttre container, olika kategorier med videor som horisontalscrollar, och video-previews ![Image](https://github.com/OwnTube-tv/web-client/assets/123388211/dc7a7b9e-c248-41c9-8ac8-0b25f4ddd315)
   - [ ] Boka ett "grooming-möte 3" och diskutera vilka komponenter som behövs och hur man ska implementera landningssidan i React Native + skapa issue för detta
   - [x] Ta olika (extremt) lågpresterande low-end devicer (Android/TV) i beaktande, antal videor att rendera per kategori? Dokumentera i React-issuet eller någon annanstans hur vi ska tänka kring detta.
- [ ] Namnge versionen från denna uppgift "landing-page-v1.0.0" och be @tryklick & @mblomdahl & @OGTor reviewa + approva

**Comment by OGTor** [comment]
> * [x] 1. Use Figma and make it easily shareable ← https://www.figma.com/file/77wSzKzV4cbKzttKpG4vPw/Untitled?type=design&node-id=0%3A1&mode=design&t=ZcSPPNIUARQPFM7M-1
> 
>     * [x] 1.1 Mock-ups på design, hur ser landningssidan ut? Ska se vettigt ut i alla förekommande formfaktorer. 2 varianter för tablet, 2 varianter för desktop, och 4 varianter för mobiler (Android/iPhone, stående/liggande)
> 
>     * [x] 1.2 Vilka komponenter behöver sidan? Förmodligen någon yttre container, olika kategorier med videor som horisontalscrollar, och video-previews 
>       
>       * [x] 1.2.1 Boka ett "grooming-möte 3" och diskutera vilka komponenter som behövs och hur man ska implementera landningssidan i React Native + skapa issue för detta
>       * [x] 1.2.2 Ta olika (extremt) lågpresterande low-end devicer (Android/TV) i beaktande, antal videor att rendera per kategori? Dokumentera i React-issuet eller någon annanstans hur vi ska tänka kring detta.
> 
>     * [x] 1.3 Namnge versionen från denna uppgift "landing-page-v1.0.0" och be @tryklick & @mblomdahl & @OGTor reviewa + approva
> 


 1.2  
React Components to implement

- MainPageComponent
 - CategoryOverviewComponent
   - VideoCategoryPreviewComponent(s)
    - VideoThumbnailComponent(s)
- Video category component
- Video preview component


Other things: 
- Data
  - Categories
  - Videos
  - Category Name
  - Videos in each Category
  - Video Title
  - Video Thumbnail image
  - Video Length
  - Video rank
