### ISSUE TITLE
Adress Yaroslav's comments on initial page layout

### ISSUE THREAD

**Issue by mblomdahl** [OwnTube-tv/web-client#38]
Address PR #34 review comments from @Dykyi:

- [x] Have different views in a `screens/` structure
- [x] Do not copy inline styling everywhere (share instead)
- [x] Make components more light-weight
- [x] Have shared types in a `types/` color
- [x] Declare colors somewhere where they can be shared
- [x] Use "layouts" in the `App.tsx`
- [x] Add a `utils/` for things like sizing functions
- [x] Use hooks for reusing

**Comment by ar9708** [comment]
Resolved in #51
