### ISSUE TITLE
Please ask Viktor to provide the OwnTube favicon + logo original pictures

### ISSUE THREAD

**Issue by mblomdahl** [OwnTube-tv/web-client#56]
From troubleshooting asset appearance with @mykhailodanilenko today, @OGTor ... Can you please upload the SVGs and generated PNGs for OwnTube web client to this GitHub issue? Just attachments here. We need to repair broken appearance.

**Comment by OGTor** [comment]
I have attached a folder with a bunch of different versions of the logos. hope this helps :D
[owntube.zip](https://github.com/OwnTube-tv/web-client/files/15452511/owntube.zip)
