### ISSUE TITLE
Support HLS on Web through video.js/hls.js

### ISSUE THREAD

**Issue by mykhailodanilenko** [OwnTube-tv/web-client#64]
1. Create a platform-specific (web) video playback component
2. The component will utilize an hls-supporting lib on the web, video.js or hls.js (investigate which is easier to use)
3. Update baseQueryParams in the video fetching service to include hls videos when fetching videos list

**Comment by freeboub** [comment]
I am not sure if I can give you good clues, but I think you can also consider shaka player!
